"""
Mochi Skills Server (MCP Sandbox)
=================================

This server automatically loads any `.py` modules inside the `skills/` directory.
It is intended to run as a separate process alongside Mochi, sandboxing any
code generated by the Learner Agent.

Run:
    python skills_server/server.py
"""

import importlib
import logging
from pathlib import Path
import sys

from mcp.server.fastmcp import FastMCP
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# The unified FastMCP server instance shared by all skills
mcp = FastMCP(
    "Mochi Skills Server",
    instructions="Sandboxed tools generated by the Learner Agent.",
)

def load_skill_module(path: Path) -> bool:
    """Load or reload a single skill module."""
    if path.name == "__init__.py" or path.name.endswith(".draft") or not path.name.endswith(".py"):
        return False
        
    module_name = f"skills_server.skills.{path.stem}"
    try:
        if module_name in sys.modules:
            importlib.reload(sys.modules[module_name])
            logger.info(f"Reloaded skill module: {module_name}")
        else:
            importlib.import_module(module_name)
            logger.info(f"Loaded new skill module: {module_name}")
        return True
    except Exception as e:
        logger.error(f"Failed to load skill module {module_name}: {e}")
        return False

def load_all_skills():
    """Initial load of all skills in the directory."""
    server_dir = Path(__file__).parent
    skills_dir = server_dir / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)
    
    # Ensure the parent directory is in sys.path so we can import 'skills_server.skills.X'
    root_dir = server_dir.parent
    if str(root_dir) not in sys.path:
        sys.path.insert(0, str(root_dir))

    loaded_count = 0
    for path in skills_dir.glob("*.py"):
        if load_skill_module(path):
            loaded_count += 1
    return loaded_count

class SkillWatcher(FileSystemEventHandler):
    """Watches the skills directory for new or modified python files."""
    def on_created(self, event):
        if not event.is_directory and event.src_path.endswith(".py"):
            logger.info(f"Detected new file: {event.src_path}")
            load_skill_module(Path(event.src_path))

    def on_modified(self, event):
        if not event.is_directory and event.src_path.endswith(".py"):
            logger.info(f"Detected modified file: {event.src_path}")
            load_skill_module(Path(event.src_path))

def start_watcher():
    """Start the watchdog observer."""
    skills_dir = Path(__file__).parent / "skills"
    event_handler = SkillWatcher()
    observer = Observer()
    observer.schedule(event_handler, str(skills_dir), recursive=False)
    observer.start()
    return observer

if __name__ == "__main__":
    count = load_all_skills()
    logger.info(f"Started Skills Server. Loaded {count} skill modules.")
    
    observer = start_watcher()
    logger.info("Watching directory for live skill deployments...")
    
    try:
        mcp.run(transport="streamable-http", host="127.0.0.1", port=8001)
    finally:
        observer.stop()
        observer.join()
